[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "eml_forensic_suite"
version = "1.0.1"
requires-python = ">=3.11"
dependencies = ["PySide6>=6.8"]

[tool.setuptools.packages.find]
where = ["src"]
